/**
 * @fileoverview gRPC-Web generated client stub for funwheel
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.1
// source: grpc/funwheel.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.funwheel = require('./funwheel_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.funwheel.FunWheelServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.funwheel.FunWheelServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.funwheel.CreateWheelRequest,
 *   !proto.funwheel.CreateWheelResponse>}
 */
const methodDescriptor_FunWheelService_CreateWheel = new grpc.web.MethodDescriptor(
  '/funwheel.FunWheelService/CreateWheel',
  grpc.web.MethodType.UNARY,
  proto.funwheel.CreateWheelRequest,
  proto.funwheel.CreateWheelResponse,
  /**
   * @param {!proto.funwheel.CreateWheelRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.funwheel.CreateWheelResponse.deserializeBinary
);


/**
 * @param {!proto.funwheel.CreateWheelRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.funwheel.CreateWheelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.funwheel.CreateWheelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.funwheel.FunWheelServiceClient.prototype.createWheel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/funwheel.FunWheelService/CreateWheel',
      request,
      metadata || {},
      methodDescriptor_FunWheelService_CreateWheel,
      callback);
};


/**
 * @param {!proto.funwheel.CreateWheelRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.funwheel.CreateWheelResponse>}
 *     Promise that resolves to the response
 */
proto.funwheel.FunWheelServicePromiseClient.prototype.createWheel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/funwheel.FunWheelService/CreateWheel',
      request,
      metadata || {},
      methodDescriptor_FunWheelService_CreateWheel);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.funwheel.AddOptionRequest,
 *   !proto.funwheel.AddOptionsResponse>}
 */
const methodDescriptor_FunWheelService_AddOption = new grpc.web.MethodDescriptor(
  '/funwheel.FunWheelService/AddOption',
  grpc.web.MethodType.UNARY,
  proto.funwheel.AddOptionRequest,
  proto.funwheel.AddOptionsResponse,
  /**
   * @param {!proto.funwheel.AddOptionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.funwheel.AddOptionsResponse.deserializeBinary
);


/**
 * @param {!proto.funwheel.AddOptionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.funwheel.AddOptionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.funwheel.AddOptionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.funwheel.FunWheelServiceClient.prototype.addOption =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/funwheel.FunWheelService/AddOption',
      request,
      metadata || {},
      methodDescriptor_FunWheelService_AddOption,
      callback);
};


/**
 * @param {!proto.funwheel.AddOptionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.funwheel.AddOptionsResponse>}
 *     Promise that resolves to the response
 */
proto.funwheel.FunWheelServicePromiseClient.prototype.addOption =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/funwheel.FunWheelService/AddOption',
      request,
      metadata || {},
      methodDescriptor_FunWheelService_AddOption);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.funwheel.SpinWheelRequest,
 *   !proto.funwheel.SpinWheelResponse>}
 */
const methodDescriptor_FunWheelService_SpinWheel = new grpc.web.MethodDescriptor(
  '/funwheel.FunWheelService/SpinWheel',
  grpc.web.MethodType.UNARY,
  proto.funwheel.SpinWheelRequest,
  proto.funwheel.SpinWheelResponse,
  /**
   * @param {!proto.funwheel.SpinWheelRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.funwheel.SpinWheelResponse.deserializeBinary
);


/**
 * @param {!proto.funwheel.SpinWheelRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.funwheel.SpinWheelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.funwheel.SpinWheelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.funwheel.FunWheelServiceClient.prototype.spinWheel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/funwheel.FunWheelService/SpinWheel',
      request,
      metadata || {},
      methodDescriptor_FunWheelService_SpinWheel,
      callback);
};


/**
 * @param {!proto.funwheel.SpinWheelRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.funwheel.SpinWheelResponse>}
 *     Promise that resolves to the response
 */
proto.funwheel.FunWheelServicePromiseClient.prototype.spinWheel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/funwheel.FunWheelService/SpinWheel',
      request,
      metadata || {},
      methodDescriptor_FunWheelService_SpinWheel);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.funwheel.ViewOptionsRequest,
 *   !proto.funwheel.ViewOptionsResponse>}
 */
const methodDescriptor_FunWheelService_ViewOptions = new grpc.web.MethodDescriptor(
  '/funwheel.FunWheelService/ViewOptions',
  grpc.web.MethodType.UNARY,
  proto.funwheel.ViewOptionsRequest,
  proto.funwheel.ViewOptionsResponse,
  /**
   * @param {!proto.funwheel.ViewOptionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.funwheel.ViewOptionsResponse.deserializeBinary
);


/**
 * @param {!proto.funwheel.ViewOptionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.funwheel.ViewOptionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.funwheel.ViewOptionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.funwheel.FunWheelServiceClient.prototype.viewOptions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/funwheel.FunWheelService/ViewOptions',
      request,
      metadata || {},
      methodDescriptor_FunWheelService_ViewOptions,
      callback);
};


/**
 * @param {!proto.funwheel.ViewOptionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.funwheel.ViewOptionsResponse>}
 *     Promise that resolves to the response
 */
proto.funwheel.FunWheelServicePromiseClient.prototype.viewOptions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/funwheel.FunWheelService/ViewOptions',
      request,
      metadata || {},
      methodDescriptor_FunWheelService_ViewOptions);
};


module.exports = proto.funwheel;

