version: "3"

services:
  bot:
    build:
      context: ./bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped

  site:
    build:
      context: ./site
    ports:
      - "80:${PORT:-8080}"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8080}
    restart: unless-stopped
