version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/server/static
    ports:
      - "8080:8080"
    networks:
      - fun-wheel-network

  telegram-bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - server
    networks:
      - fun-wheel-network

networks:
  fun-wheel-network:
    driver: bridge 