version: "3"

services:
  bot:
    build:
      context: ./bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped

  site:
    build:
      context: ./site
    ports:
      - "8080:8080"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8080}
    networks:
      - fortune-wheel-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/nginx/certs  # Путь к вашим сертификатам
    ports:
      - "80:80"
      - "443:443"
    networks:
      - fortune-wheel-network
    depends_on:
      - site
    restart: unless-stopped

networks:
  fortune-wheel-network:
    driver: bridge
