// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.2
// source: grpc/funwheel.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWheelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
}

func (x *CreateWheelRequest) Reset() {
	*x = CreateWheelRequest{}
	mi := &file_grpc_funwheel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWheelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWheelRequest) ProtoMessage() {}

func (x *CreateWheelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_funwheel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWheelRequest.ProtoReflect.Descriptor instead.
func (*CreateWheelRequest) Descriptor() ([]byte, []int) {
	return file_grpc_funwheel_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWheelRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type CreateWheelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateWheelResponse) Reset() {
	*x = CreateWheelResponse{}
	mi := &file_grpc_funwheel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWheelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWheelResponse) ProtoMessage() {}

func (x *CreateWheelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_funwheel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWheelResponse.ProtoReflect.Descriptor instead.
func (*CreateWheelResponse) Descriptor() ([]byte, []int) {
	return file_grpc_funwheel_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWheelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId int64  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Option string `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
}

func (x *AddOptionRequest) Reset() {
	*x = AddOptionRequest{}
	mi := &file_grpc_funwheel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOptionRequest) ProtoMessage() {}

func (x *AddOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_funwheel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOptionRequest.ProtoReflect.Descriptor instead.
func (*AddOptionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_funwheel_proto_rawDescGZIP(), []int{2}
}

func (x *AddOptionRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *AddOptionRequest) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

type AddOptionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddOptionsResponse) Reset() {
	*x = AddOptionsResponse{}
	mi := &file_grpc_funwheel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOptionsResponse) ProtoMessage() {}

func (x *AddOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_funwheel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOptionsResponse.ProtoReflect.Descriptor instead.
func (*AddOptionsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_funwheel_proto_rawDescGZIP(), []int{3}
}

func (x *AddOptionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SpinWheelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
}

func (x *SpinWheelRequest) Reset() {
	*x = SpinWheelRequest{}
	mi := &file_grpc_funwheel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinWheelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinWheelRequest) ProtoMessage() {}

func (x *SpinWheelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_funwheel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinWheelRequest.ProtoReflect.Descriptor instead.
func (*SpinWheelRequest) Descriptor() ([]byte, []int) {
	return file_grpc_funwheel_proto_rawDescGZIP(), []int{4}
}

func (x *SpinWheelRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type SpinWheelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SpinWheelResponse) Reset() {
	*x = SpinWheelResponse{}
	mi := &file_grpc_funwheel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinWheelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinWheelResponse) ProtoMessage() {}

func (x *SpinWheelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_funwheel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinWheelResponse.ProtoReflect.Descriptor instead.
func (*SpinWheelResponse) Descriptor() ([]byte, []int) {
	return file_grpc_funwheel_proto_rawDescGZIP(), []int{5}
}

func (x *SpinWheelResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ViewOptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
}

func (x *ViewOptionsRequest) Reset() {
	*x = ViewOptionsRequest{}
	mi := &file_grpc_funwheel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewOptionsRequest) ProtoMessage() {}

func (x *ViewOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_funwheel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewOptionsRequest.ProtoReflect.Descriptor instead.
func (*ViewOptionsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_funwheel_proto_rawDescGZIP(), []int{6}
}

func (x *ViewOptionsRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type ViewOptionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options []string `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *ViewOptionsResponse) Reset() {
	*x = ViewOptionsResponse{}
	mi := &file_grpc_funwheel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewOptionsResponse) ProtoMessage() {}

func (x *ViewOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_funwheel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewOptionsResponse.ProtoReflect.Descriptor instead.
func (*ViewOptionsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_funwheel_proto_rawDescGZIP(), []int{7}
}

func (x *ViewOptionsResponse) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_grpc_funwheel_proto protoreflect.FileDescriptor

var file_grpc_funwheel_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x75, 0x6e, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x75, 0x6e, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x22,
	0x2d, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x22, 0x2f,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x43, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x10, 0x53, 0x70, 0x69, 0x6e, 0x57, 0x68, 0x65, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49,
	0x64, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x70, 0x69, 0x6e, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2d,
	0x0a, 0x12, 0x56, 0x69, 0x65, 0x77, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x22, 0x2f, 0x0a,
	0x13, 0x56, 0x69, 0x65, 0x77, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xb6,
	0x02, 0x0a, 0x0f, 0x46, 0x75, 0x6e, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x68, 0x65, 0x65,
	0x6c, 0x12, 0x1c, 0x2e, 0x66, 0x75, 0x6e, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x66, 0x75, 0x6e, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45,
	0x0a, 0x09, 0x41, 0x64, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x66, 0x75,
	0x6e, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x75, 0x6e, 0x77, 0x68, 0x65,
	0x65, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x53, 0x70, 0x69, 0x6e, 0x57, 0x68, 0x65,
	0x65, 0x6c, 0x12, 0x1a, 0x2e, 0x66, 0x75, 0x6e, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x2e, 0x53, 0x70,
	0x69, 0x6e, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x66, 0x75, 0x6e, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x2e, 0x53, 0x70, 0x69, 0x6e, 0x57, 0x68,
	0x65, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x56,
	0x69, 0x65, 0x77, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x66, 0x75, 0x6e,
	0x77, 0x68, 0x65, 0x65, 0x6c, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x75, 0x6e, 0x77, 0x68,
	0x65, 0x65, 0x6c, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_funwheel_proto_rawDescOnce sync.Once
	file_grpc_funwheel_proto_rawDescData = file_grpc_funwheel_proto_rawDesc
)

func file_grpc_funwheel_proto_rawDescGZIP() []byte {
	file_grpc_funwheel_proto_rawDescOnce.Do(func() {
		file_grpc_funwheel_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_funwheel_proto_rawDescData)
	})
	return file_grpc_funwheel_proto_rawDescData
}

var file_grpc_funwheel_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_funwheel_proto_goTypes = []any{
	(*CreateWheelRequest)(nil),  // 0: funwheel.CreateWheelRequest
	(*CreateWheelResponse)(nil), // 1: funwheel.CreateWheelResponse
	(*AddOptionRequest)(nil),    // 2: funwheel.AddOptionRequest
	(*AddOptionsResponse)(nil),  // 3: funwheel.AddOptionsResponse
	(*SpinWheelRequest)(nil),    // 4: funwheel.SpinWheelRequest
	(*SpinWheelResponse)(nil),   // 5: funwheel.SpinWheelResponse
	(*ViewOptionsRequest)(nil),  // 6: funwheel.ViewOptionsRequest
	(*ViewOptionsResponse)(nil), // 7: funwheel.ViewOptionsResponse
}
var file_grpc_funwheel_proto_depIdxs = []int32{
	0, // 0: funwheel.FunWheelService.CreateWheel:input_type -> funwheel.CreateWheelRequest
	2, // 1: funwheel.FunWheelService.AddOption:input_type -> funwheel.AddOptionRequest
	4, // 2: funwheel.FunWheelService.SpinWheel:input_type -> funwheel.SpinWheelRequest
	6, // 3: funwheel.FunWheelService.ViewOptions:input_type -> funwheel.ViewOptionsRequest
	1, // 4: funwheel.FunWheelService.CreateWheel:output_type -> funwheel.CreateWheelResponse
	3, // 5: funwheel.FunWheelService.AddOption:output_type -> funwheel.AddOptionsResponse
	5, // 6: funwheel.FunWheelService.SpinWheel:output_type -> funwheel.SpinWheelResponse
	7, // 7: funwheel.FunWheelService.ViewOptions:output_type -> funwheel.ViewOptionsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_funwheel_proto_init() }
func file_grpc_funwheel_proto_init() {
	if File_grpc_funwheel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_funwheel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_funwheel_proto_goTypes,
		DependencyIndexes: file_grpc_funwheel_proto_depIdxs,
		MessageInfos:      file_grpc_funwheel_proto_msgTypes,
	}.Build()
	File_grpc_funwheel_proto = out.File
	file_grpc_funwheel_proto_rawDesc = nil
	file_grpc_funwheel_proto_goTypes = nil
	file_grpc_funwheel_proto_depIdxs = nil
}
